In [2]:
import sklearn 
from sklearn.cluster import KMeans
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.datasets import load_iris

In [6]:
Flower = load_iris()

In [7]:
dir(Flower)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [11]:
df = pd.DataFrame(Flower.data,columns=Flower.feature_names)
df.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [12]:
Final = df.drop(['sepal length (cm)', 'sepal width (cm)'], axis = 'columns')
Final.head()

   petal length (cm)  petal width (cm)
0                1.4               0.2
1                1.4               0.2
2                1.3               0.2
3                1.5               0.2
4                1.4               0.2

In [22]:
scaler_length = MinMaxScaler()
scaler_length.fit(Final[['petal length (cm)']])
Final['Petal_Length'] = scaler_length.transform(Final[['petal length (cm)']])
scaler_width = MinMaxScaler()
scaler_width.fit(Final[['petal width (cm)']])
Final['Petal_Width'] = scaler_width.transform(Final[['petal width (cm)']])
Final.head()

   petal length (cm)  petal width (cm)  Petal_Length  Petal_Width
0                1.4               0.2      0.067797     0.041667
1                1.4               0.2      0.067797     0.041667
2                1.3               0.2      0.050847     0.041667
3                1.5               0.2      0.084746     0.041667
4                1.4               0.2      0.067797     0.041667

In [23]:
Necessary = Final.drop(['petal length (cm)', 'petal width (cm)'], axis = 'columns')
Necessary.head()

   Petal_Length  Petal_Width
0      0.067797     0.041667
1      0.067797     0.041667
2      0.050847     0.041667
3      0.084746     0.041667
4      0.067797     0.041667

In [30]:
KM = KMeans(n_clusters = 3)
y_predict = KM.fit_predict(Necessary[['Petal_Length', 'Petal_Width']])

C:\Users\srini\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1419: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(

In [32]:
Necessary['Cluster'] = y_predict
Necessary.head()

   Petal_Length  Petal_Width  Cluster
0      0.067797     0.041667        1
1      0.067797     0.041667        1
2      0.050847     0.041667        1
3      0.084746     0.041667        1
4      0.067797     0.041667        1

In [ ]:
plt