In [7]:
import pandas as pd
import sklearn.linear_model
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import matplotlib
from matplotlib import pyplot as plt
%matplotlib inline

In [4]:
df = pd.read_csv("C:/Users/srini/Downloads/HR_comma_sep.csv")
df.head()

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,Department,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.11,0.88,7,272,4,0,1,0,sales,medium
3,0.72,0.87,5,223,5,0,1,0,sales,low
4,0.37,0.52,2,159,3,0,1,0,sales,low

In [33]:
Required_df = df[['satisfaction_level', 'average_montly_hours', 'promotion_last_5years', 'salary', 'left']]
Required_df.head()

,satisfaction_level,average_montly_hours,promotion_last_5years,salary,left
0,0.38,157,0,low,1
1,0.80,262,0,medium,1
2,0.11,272,0,medium,1
3,0.72,223,0,low,1
4,0.37,159,0,low,1

In [34]:
Dummy = pd.get_dummies(df.salary, prefix="salary")
Dummy.head()

   salary_high  salary_low  salary_medium
0        False        True          False
1        False       False           True
2        False       False           True
3        False        True          False
4        False        True          False

In [35]:
merged = pd.concat([Required_df, Dummy], axis = 'columns')
merged.head()

,satisfaction_level,average_montly_hours,promotion_last_5years,salary,left,salary_high,salary_low,salary_medium
0,0.38,157,0,low,1,False,True,False
1,0.80,262,0,medium,1,False,False,True
2,0.11,272,0,medium,1,False,False,True
3,0.72,223,0,low,1,False,True,False
4,0.37,159,0,low,1,False,True,False

In [36]:
final = merged.drop(['salary'], axis= 'columns')
final.head()

,satisfaction_level,average_montly_hours,promotion_last_5years,left,salary_high,salary_low,salary_medium
0,0.38,157,0,1,False,True,False
1,0.80,262,0,1,False,False,True
2,0.11,272,0,1,False,False,True
3,0.72,223,0,1,False,True,False
4,0.37,159,0,1,False,True,False

In [39]:
X = final.drop(['left'], axis = 'columns')
Y = df.left
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2)

In [ ]:
model  = LogisticRegression()
model.fit(